In [56]:
import numpy as np
import pandas as pd

In [57]:
label = pd.read_csv('label.csv')
label

      image  label
0         0     77
1         1     77
2         2     77
3         3     77
4         4     77
5         5     77
6         6     77
7         7     77
8         8     77
9         9     77
10       10     77
11       11     77
12       12     77
13       13     77
14       14     77
15       15     77
16       16     77
17       17     77
18       18     77
19       19     77
20       20     77
21       21     77
22       22     77
23       23     77
24       24     77
25       25     77
26       26     77
27       27     77
28       28     77
29       29     77
...     ...    ...
8159   8159     62
8160   8160     62
8161   8161     62
8162   8162     62
8163   8163     62
8164   8164     62
8165   8165     62
8166   8166     62
8167   8167     62
8168   8168     62
8169   8169     62
8170   8170     62
8171   8171     62
8172   8172     62
8173   8173     62
8174   8174     62
8175   8175     62
8176   8176     62
8177   8177     62
8178   8178     62
8179   8179     62
8180   8180     62
8181   8181     62
8182   8182     62
8183   8183     62
8184   8184     62
8185   8185     62
8186   8186     62
8187   8187     62
8188   8188     62

[8189 rows x 2 columns]

In [58]:
num = pd.read_csv('num.csv')
num

                        label  num
0                     petunia  258
1              passion flower  251
2                  wallflower  196
3                  water lily  194
4                  watercress  184
5                        rose  171
6                  frangipani  166
7                    foxglove  162
8                   cyclamen   154
9                       lotus  137
10                   hibiscus  131
11                 sword lily  130
12              bougainvillea  128
13             barbeton daisy  127
14                thorn apple  120
15                   geranium  114
16                   clematis  112
17         bishop of llandaff  109
18        pink-yellow dahlia?  109
19                cape flower  108
20              morning glory  107
21                  anthurium  105
22          californian poppy  102
23                     azalea   96
24                 poinsettia   93
25                    primula   93
26           common dandelion   92
27                   camellia   91
28                 fritillary   91
29                colt's foot   87
..                        ...  ...
72                 silverbush   52
73           cautleya spicata   50
74             balloon flower   49
75             blanket flower   49
76                king protea   49
77                oxeye daisy   49
78                yellow iris   49
79            blackberry lily   48
80              spear thistle   48
81                  ball moss   46
82           love in the mist   46
83                  monkshood   46
84               garden phlox   45
85              globe thistle   45
86                 tiger lily   45
87           alpine sea holly   43
88                 red ginger   42
89              spring crocus   42
90                 corn poppy   41
91                 siam tulip   41
92               globe-flower   41
93             grape hyacinth   41
94                  toad lily   41
95           bolero deep blue   40
96              mexican aster   40
97                moon orchid   40
98           canterbury bells   40
99              pink primrose   40
100  prince of wales feathers   40
101                 fire lily   40

[102 rows x 2 columns]

In [59]:
sum(num['num'])

8189

In [60]:
cnts = label['label'].value_counts()

In [61]:
cnts

51     258
77     251
46     196
73     194
89     184
74     171
81     166
94     162
88     154
78     137
83     131
43     130
95     128
41     127
75     120
58     114
82     112
56     109
60     109
37     108
76     107
80     105
65     102
72      96
53      93
44      93
50      92
23      91
96      91
11      87
      ...
64      52
61      50
49      49
19      49
15      49
13      49
100     49
14      48
102     48
33      46
93      46
9       46
10      45
32      45
6       45
35      43
24      42
67      42
79      41
16      41
25      41
26      41
39      41
45      40
34      40
27      40
21      40
7       40
1       40
3       40
Name: label, Length: 102, dtype: int64

In [62]:
temp = num.copy()

In [63]:
temp = temp.sort_values(by='num', ascending=False)

In [64]:
temp

                        label  num
0                     petunia  258
1              passion flower  251
2                  wallflower  196
3                  water lily  194
4                  watercress  184
5                        rose  171
6                  frangipani  166
7                    foxglove  162
8                   cyclamen   154
9                       lotus  137
10                   hibiscus  131
11                 sword lily  130
12              bougainvillea  128
13             barbeton daisy  127
14                thorn apple  120
15                   geranium  114
16                   clematis  112
17         bishop of llandaff  109
18        pink-yellow dahlia?  109
19                cape flower  108
20              morning glory  107
21                  anthurium  105
22          californian poppy  102
23                     azalea   96
25                    primula   93
24                 poinsettia   93
26           common dandelion   92
27                   camellia   91
28                 fritillary   91
29                colt's foot   87
..                        ...  ...
72                 silverbush   52
73           cautleya spicata   50
78                yellow iris   49
77                oxeye daisy   49
76                king protea   49
75             blanket flower   49
74             balloon flower   49
79            blackberry lily   48
80              spear thistle   48
81                  ball moss   46
82           love in the mist   46
83                  monkshood   46
84               garden phlox   45
85              globe thistle   45
86                 tiger lily   45
87           alpine sea holly   43
89              spring crocus   42
88                 red ginger   42
90                 corn poppy   41
91                 siam tulip   41
92               globe-flower   41
93             grape hyacinth   41
94                  toad lily   41
95           bolero deep blue   40
96              mexican aster   40
97                moon orchid   40
98           canterbury bells   40
99              pink primrose   40
100  prince of wales feathers   40
101                 fire lily   40

[102 rows x 2 columns]

In [65]:
type(cnts)

pandas.core.series.Series

In [66]:
type(temp)

pandas.core.frame.DataFrame

In [67]:
cnts = pd.DataFrame({'id': cnts.index, 'idnum': cnts.values})

In [68]:
cnts

      id  idnum
0     51    258
1     77    251
2     46    196
3     73    194
4     89    184
5     74    171
6     81    166
7     94    162
8     88    154
9     78    137
10    83    131
11    43    130
12    95    128
13    41    127
14    75    120
15    58    114
16    82    112
17    56    109
18    60    109
19    37    108
20    76    107
21    80    105
22    65    102
23    72     96
24    53     93
25    44     93
26    50     92
27    23     91
28    96     91
29    11     87
..   ...    ...
72    64     52
73    61     50
74    49     49
75    19     49
76    15     49
77    13     49
78   100     49
79    14     48
80   102     48
81    33     46
82    93     46
83     9     46
84    10     45
85    32     45
86     6     45
87    35     43
88    24     42
89    67     42
90    79     41
91    16     41
92    25     41
93    26     41
94    39     41
95    45     40
96    34     40
97    27     40
98    21     40
99     7     40
100    1     40
101    3     40

[102 rows x 2 columns]

In [70]:
total = pd.concat([temp, cnts], axis=1)

In [71]:
total

                        label  num   id  idnum
0                     petunia  258   51    258
1              passion flower  251   77    251
2                  wallflower  196   46    196
3                  water lily  194   73    194
4                  watercress  184   89    184
5                        rose  171   74    171
6                  frangipani  166   81    166
7                    foxglove  162   94    162
8                   cyclamen   154   88    154
9                       lotus  137   78    137
10                   hibiscus  131   83    131
11                 sword lily  130   43    130
12              bougainvillea  128   95    128
13             barbeton daisy  127   41    127
14                thorn apple  120   75    120
15                   geranium  114   58    114
16                   clematis  112   82    112
17         bishop of llandaff  109   56    109
18        pink-yellow dahlia?  109   60    109
19                cape flower  108   37    108
20              morning glory  107   76    107
21                  anthurium  105   80    105
22          californian poppy  102   65    102
23                     azalea   96   72     96
24                 poinsettia   93   53     93
25                    primula   93   44     93
26           common dandelion   92   50     92
27                   camellia   91   23     91
28                 fritillary   91   96     91
29                colt's foot   87   11     87
..                        ...  ...  ...    ...
72                 silverbush   52   64     52
73           cautleya spicata   50   61     50
74             balloon flower   49   49     49
75             blanket flower   49   19     49
76                king protea   49   15     49
77                oxeye daisy   49   13     49
78                yellow iris   49  100     49
79            blackberry lily   48   14     48
80              spear thistle   48  102     48
81                  ball moss   46   33     46
82           love in the mist   46   93     46
83                  monkshood   46    9     46
84               garden phlox   45   10     45
85              globe thistle   45   32     45
86                 tiger lily   45    6     45
87           alpine sea holly   43   35     43
88                 red ginger   42   24     42
89              spring crocus   42   67     42
90                 corn poppy   41   79     41
91                 siam tulip   41   16     41
92               globe-flower   41   25     41
93             grape hyacinth   41   26     41
94                  toad lily   41   39     41
95           bolero deep blue   40   45     40
96              mexican aster   40   34     40
97                moon orchid   40   27     40
98           canterbury bells   40   21     40
99              pink primrose   40    7     40
100  prince of wales feathers   40    1     40
101                 fire lily   40    3     40

[102 rows x 4 columns]

In [73]:
pd.set_option('display.max_rows', None)
total.loc[0:77]

                        label  num   id  idnum
0                     petunia  258   51    258
1              passion flower  251   77    251
2                  wallflower  196   46    196
3                  water lily  194   73    194
4                  watercress  184   89    184
5                        rose  171   74    171
6                  frangipani  166   81    166
7                    foxglove  162   94    162
8                   cyclamen   154   88    154
9                       lotus  137   78    137
10                   hibiscus  131   83    131
11                 sword lily  130   43    130
12              bougainvillea  128   95    128
13             barbeton daisy  127   41    127
14                thorn apple  120   75    120
15                   geranium  114   58    114
16                   clematis  112   82    112
17         bishop of llandaff  109   56    109
18        pink-yellow dahlia?  109   60    109
19                cape flower  108   37    108
20              morning glory  107   76    107
21                  anthurium  105   80    105
22          californian poppy  102   65    102
23                     azalea   96   72     96
24                 poinsettia   93   53     93
25                    primula   93   44     93
26           common dandelion   92   50     92
27                   camellia   91   23     91
28                 fritillary   91   96     91
29                colt's foot   87   11     87
30                 snapdragon   87   12     87
31                  columbine   86   84     86
32           bird of paradise   85    8     85
33          purple coneflower   85   17     85
34              sweet william   85   30     85
35                 wild pansy   85   52     85
36            mexican petunia   82   18     82
37                 canna lily   82   90     82
38              peruvian lily   82   98     82
39                  artichoke   78   71     78
40                    gazania   78   29     78
41               hippeastrum    76   91     76
42       ruby-lipped cattleya   75   36     75
43                pelargonium   71   55     71
44                  buttercup   71   48     71
45                lenten rose   67   57     67
46                   marigold   67   40     67
47              orange dahlia   67   47     67
48                      gaura   67   59     67
49                   bee balm   66   92     66
50                     mallow   66   97     66
51           stemless gentian   66   28     66
52           english marigold   65    5     65
53                   bromelia   63   85     63
54                   magnolia   63   87     63
55                desert-rose   63   99     63
56                 tree poppy   62   70     62
57               osteospermum   61   54     61
58                  sunflower   61   66     61
59  hard-leaved pocket orchid   60    2     60
60                   daffodil   59   22     59
61          pincushion flower   59   42     59
62                tree mallow   58  101     58
63            trumpet creeper   58   86     58
64      giant white arum lily   56   38     56
65           great masterwort   56   20     56
66                  sweet pea   56    4     56
67           japanese anemone   55   62     55
68               bearded iris   54   63     54
69           black-eyed susan   54   68     54
70                 windflower   54   69     54
71                  carnation   52   31     52
72                 silverbush   52   64     52
73           cautleya spicata   50   61     50
74             balloon flower   49   49     49
75             blanket flower   49   19     49
76                king protea   49   15     49
77                oxeye daisy   49   13     49

In [74]:
total.loc[0:30]

                  label  num  id  idnum
0               petunia  258  51    258
1        passion flower  251  77    251
2            wallflower  196  46    196
3            water lily  194  73    194
4            watercress  184  89    184
5                  rose  171  74    171
6            frangipani  166  81    166
7              foxglove  162  94    162
8             cyclamen   154  88    154
9                 lotus  137  78    137
10             hibiscus  131  83    131
11           sword lily  130  43    130
12        bougainvillea  128  95    128
13       barbeton daisy  127  41    127
14          thorn apple  120  75    120
15             geranium  114  58    114
16             clematis  112  82    112
17   bishop of llandaff  109  56    109
18  pink-yellow dahlia?  109  60    109
19          cape flower  108  37    108
20        morning glory  107  76    107
21            anthurium  105  80    105
22    californian poppy  102  65    102
23               azalea   96  72     96
24           poinsettia   93  53     93
25              primula   93  44     93
26     common dandelion   92  50     92
27             camellia   91  23     91
28           fritillary   91  96     91
29          colt's foot   87  11     87
30           snapdragon   87  12     87

In [75]:
total.to_csv('total.csv')